# Generated by Django 3.1.4 on 2020-12-08 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('icon', models.ImageField(default='default-image-620x600.jpg', upload_to='icons/', verbose_name='Icon')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='End date')),
                ('user', models.CharField(default='1', max_length=150, verbose_name='User id')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
